/*
 * ecodata - OpenAPI 3.0
 *
 * API to store contamination events and data from different sources
 *
 * API version: 1.0.0
 * Contact: nestor.salvador@gdl.cinvestav.mx
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Bundle struct {

	Id string `json:"id,omitempty"`

	// Bundle Status
	BundleStatus string `json:"bundleStatus,omitempty"`
}
